import type { Testimonial } from "@/types/testimonial";

export const testimonials: Testimonial[] = [
  {
    id: 1,
    name: "Alex Sánchez",
    initials: "AS",
    text: "Siempre he tenido pánico al dentista y ha sido el único capaz de transmitirme tranquilidad y confianza.",
    treatment: "Atención sin ansiedad",
    since: "Paciente satisfecho",
    rating: 5,
  },
  {
    id: 2,
    name: "Pedro De la Iglesia",
    initials: "PI",
    text: "Confío plenamente en el Dr. Rafael y su equipo. Me han cuidado desde que era niño y el trato siempre ha sido cercano y amable.",
    treatment: "Atención dental familiar",
    since: "Paciente de largo recorrido",
    rating: 5,
  },
  {
    id: 3,
    name: "Carmen Escalera Leiva",
    initials: "CE",
    text: "Una clínica dental muy cercana y familiar. La atención del doctor Rafael es estupenda y el equipo está siempre pendiente del paciente.",
    treatment: "Clínica familiar",
    since: "Paciente satisfecha",
    rating: 5,
  },
  {
    id: 4,
    name: "RafaS",
    initials: "RS",
    text: "Atención magnífica, equipo amable y eficiente, y un trabajo muy preciso. Todo fue rápido y cómodo.",
    treatment: "Atención precisa y cómoda",
    since: "Paciente reciente",
    rating: 5,
  },
  {
    id: 5,
    name: "Laura Ortiz",
    initials: "LO",
    text: "Muy amable y simpático, te hace estar tranquila. Buena relación calidad/precio.",
    treatment: "Trato cercano",
    since: "Paciente satisfecha",
    rating: 5,
  },
  {
    id: 6,
    name: "Antonio Pulido",
    initials: "AP",
    text: "Gran profesional. Muy contento con el servicio, el trato y el resultado. Muy recomendable.",
    treatment: "Servicio muy recomendable",
    since: "Paciente satisfecho",
    rating: 5,
  },
];
